# Render manifest: defines two services — backend (web service) and frontend (static site)
services:
  - type: web
    name: marketplace-backend
    env: node
    plan: free
    region: oregon
    root: server
    buildCommand: "npm install"
    startCommand: "npm start"
    # You should configure the following environment variables in the Render dashboard
    envVars:
      - key: NODE_ENV
        value: production
    # Note: don't store secrets inside render.yaml in plaintext; set them in the Render dashboard
  # Example env vars to set in the Render dashboard for this service:
  # DATABASE_URL, JWT_SECRET, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, CLOUDINARY_CLOUD_NAME

  - type: static
    name: marketplace-frontend
    env: static
    plan: free
    region: oregon
    root: .
    # Run install with CI for repeatable builds, then run the Vite build at repo root
    buildCommand: "npm ci && npm run build"
    # Vite outputs to `dist` by default (at the repo root). Ensure Render publishes this folder.
    publishPath: "dist"

jobs:
  - type: job
    name: run-migrations
    env: node
    plan: free
    region: oregon
    root: server
    steps:
      - command: "npm install"
      - command: "npm run migrate"
    # This job should be run manually or added to a deploy hook to run before backend deployment
